### ISSUE TITLE
Failure installing npm dependency specified with full URL

### ISSUE THREAD

**Issue by gonvaled** [tonycoco/heroku-buildpack-ember-cli#119]
I have created an ember-cli heroku instance:

```
heroku create xxx-yyy-uuu --buildpack https://github.com/tonycoco/heroku-buildpack-ember-cli.git
```

And deployed to it:

```
git push heroku
```

But it fails:
```
remote: bower ember#^2.0.0        invalid-meta ember is missing "ignore" entry in bower.json                                                                                                                 [6/2258]
remote: bower ember#>=1.4         invalid-meta ember is missing "ignore" entry in bower.json
remote: bower ember#> 1.5.0-beta.3     invalid-meta ember is missing "ignore" entry in bower.json
remote: -----> Cleaning up node-gyp and npm artifacts
remote: -----> Building Ember CLI application production distribution
remote: 
remote: Missing npm packages: 
remote: Package: ember-cli-simple-auth-token
remote:   * Specified: git://github.com/jpadilla/ember-cli-simple-auth-token.git
remote:   * Installed: (not installed)
remote: 
remote: Run `npm install` to install missing dependencies.
remote: 
remote: 
remote:  !     Push rejected, failed to compile Ember CLI app
remote: 
remote: Verifying deploy....
remote: 
remote: !       Push rejected to xxx-yyy-uuu.
remote: 
To https://git.heroku.com/xxx-yyy-uuu.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/xxx-yyy-uuu.git'
```

How can the npm package be installed?

**Comment by a17levine** [comment]
Mine is failing with this, seems like it might be related?

```
remote: -----> Building Ember CLI application production distribution
remote:        `libsass` bindings not found. Try reinstalling `node-sass`?
remote:        Error: `libsass` bindings not found. Try reinstalling `node-sass`?
remote:            at getBinding (/app/tmp/cache/node_modules/node-sass/lib/index.js:22:11)
remote:            at Object.<anonymous> (/app/tmp/cache/node_modules/node-sass/lib/index.js:188:23)
remote:            at Module._compile (module.js:425:26)
remote:            at Object.Module._extensions..js (module.js:432:10)
remote:            at Module.load (module.js:356:32)
remote:            at Function.Module._load (module.js:313:12)
remote:            at Module.require (module.js:366:17)
remote:            at require (module.js:385:17)
remote:            at Object.<anonymous> (/app/tmp/cache/node_modules/broccoli-sass/index.js:5:12)
remote:            at Module._compile (module.js:425:26)
remote:
remote:  !     Push rejected, failed to compile Ember CLI app
```
