### ISSUE TITLE
Deploying after ember-cli upgrade

### ISSUE THREAD

**Issue by omairvaiyani** [tonycoco/heroku-buildpack-ember-cli#75]
Are there protocols to follow after doing an ember-cli upgrade? Because I followed all instructions to upgrade my project locally (from 0.2.1 to 0.2.2) and it works fine - however, when deploying to heroku, even with cache disabled, I get a failed build. Here's the error if it helps:

```
Caching bower_components directory for future builds
remote: -----> Building Ember CLI application production distribution
remote:        version: 0.2.2
remote:        0.2.2
remote:        
remote:        Could not find watchman, falling back to NodeWatcher for file system events.
remote:        Visit http://www.ember-cli.com/#watchman for more info.
remote:        BuildingBuilding.Building..Building...BuildingBuild failed.
remote:        Path or pattern "bower_components/ember-cli-moment-shim/moment-shim.js" did not match any files
remote:        Error: Path or pattern "bower_components/ember-cli-moment-shim/moment-shim.js" did not match any files
remote:            at Object.multiGlob (/tmp/build_77852d536a76a9e8cbd8c8f0da233c45/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
```

**Comment by tonycoco** [comment]
https://github.com/tonycoco/heroku-buildpack-ember-cli#troubleshooting

**Comment by omairvaiyani** [comment]
Hi Tony, I did that locally - I don't actually know if those actions somehow need to be taken on the heroku dyno?

**Comment by tonycoco** [comment]
It looks to me like something with the moment-shim is goofed up. I just updated my test repo and deployed just fine. Could you post your `package.json` and `bower.json`?

**Comment by omairvaiyani** [comment]
Appreciate your help!

bower.json
```
 {
  "name": "app-name",
  "dependencies": {
    "jquery": "~2.1.3",
    "ember": "1.10.0",
    "ember-data": "1.0.0-beta.16.1",
    "ember-resolver": "~0.1.15",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.3.0",
    "ember-qunit-notifications": "0.0.7",
    "qunit": "~1.17.1",
    "bootstrap": "~3.2.0",
    "font-awesome": "~4.2.0",
    "moment": "~2.9.0",
    "parse-js-sdk": "~1.3.1",
    "ember-simple-auth": "0.6.7",
    "fullcalendar": "~2.3.1",
    "firebase": "~2.1.0",
    "underscore": "~1.8.2",
    "moment-range": "~1.0.7",
    "numeral": "~1.5.3"
  },
  "resolutions": {
    "jquery": "~2.1.1"
  }
}
```
package.json
```
{
  "name": "app-name",
  "version": "0.4.0",
  "description": "---",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "Omair Vaiyani",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "^0.2.2",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^4.0.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.16.1",
    "ember-export-application-global": "^1.0.2",
    "ember-bootstrap-datetimepicker": "^0.2.8",
    "ember-cli-async-button": "^0.3.1",
    "ember-cli-datepicker": "^1.3.0",
    "ember-cli-simple-auth": "^0.6.7",
    "ember-cli-stylus": "^1.0.1",
    "ember-cli-tooltipster": "0.0.6",
    "ember-google-map": "0.0.13",
    "ember-notify": "^3.0.15",
    "ember-radio-button": "^0.1.3",
    "emberfire": "1.4.2"
  }
}
```
I ran the troubleshooting commands just now (locally) and replicated the error locally with ember-cli 0.2.3. Here's the log:

```
Error: Path or pattern "bower_components/ember-cli-moment-shim/moment-shim.js" did not match any files
    at Object.multiGlob (/Users/****/Documents/github/app-name/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
```

**Comment by omairvaiyani** [comment]
Okay so I've fixed it myself by adding ``ember-cli-moment-shim``` to bower, seems like a very obvious fix but I wasn't aware of this repository and for whatever reason, ```moment.js``` needs it now. I'll go ahead and close this issue.

**Comment by tonycoco** [comment]
Awesome. Let me know if something else blows up :)
