### ISSUE TITLE
ENOENT, no such file or directory 'node_modules/ember-cli-ic-ajax/node_modules/'

### ISSUE THREAD

**Issue by jme783** [tonycoco/heroku-buildpack-ember-cli#97]
I am running into the following deploy error, at the very tail end of the deploy:

```
Could not find watchman, falling back to NodeWatcher for file system events.
       Visit http://www.ember-cli.com/#watchman for more info.
       BuildingBuilding.Building..Building...Build failed.
       ENOENT, no such file or directory 'node_modules/ember-cli-ic-ajax/node_modules/'
       Error: ENOENT, no such file or directory 'node_modules/ember-cli-ic-ajax/node_modules/'
           at Object.fs.readdirSync (fs.js:666:18)
           at /tmp/build_41eb1c7e5d92af3ce0b088b7fb26b18b/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:32:21
           at Array.map (native)
           at mergeRelativePath (/tmp/build_41eb1c7e5d92af3ce0b088b7fb26b18b/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:29)
           at /tmp/build_41eb1c7e5d92af3ce0b088b7fb26b18b/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
           at lib$rsvp$$internal$$tryCatch (/tmp/build_41eb1c7e5d92af3ce0b088b7fb26b18b/node_modules/rsvp/dist/rsvp.js:493:16)
           at lib$rsvp$$internal$$invokeCallback (/tmp/build_41eb1c7e5d92af3ce0b088b7fb26b18b/node_modules/rsvp/dist/rsvp.js:505:17)
           at lib$rsvp$$internal$$publish (/tmp/build_41eb1c7e5d92af3ce0b088b7fb26b18b/node_modules/rsvp/dist/rsvp.js:476:11)
           at Object.lib$rsvp$asap$$flush [as _onImmediate] (/tmp/build_41eb1c7e5d92af3ce0b088b7fb26b18b/node_modules/rsvp/dist/rsvp.js:1198:9)
           at processImmediate [as _immediateCallback] (timers.js:363:15)
 !     Push rejected, failed to compile Ember CLI app
```

This is clearly an issue with the `ember-cli-ic-ajax` dependency, but I can't seem to figure out why this is blowing up. I have tried upgrading the version of the module from `0.1.1` to 0.1.2` (and higher patch versions), but this does not work, and throws a different build error.

I have flushed Heroku cache, as well as forced rebuilding of `node_modules`. This error is especially frustrating as it occurs at the very end of the build, which takes ~15 minutes.

Any help would be GREATLY appreciated. Running out of ideas here. This runs just fine on my local, even after bomb and rebuilding my `node_modules` directory

Thanks,

Jeff

**Comment by jme783** [comment]
For anyone else who runs into it, the recent release of the new `npm` caused this build issue. I had to pin `npm` at version `2.14.3` in my `package.json` to avoid this error:

```
  "engines": {
    "node": "0.12.7",
    "npm": "2.14.3"
  }
```

**Comment by patrickberkeley** [comment]
@jme783 ran into this too. Your fix worked. Thanks!

**Comment by danconnell** [comment]
https://github.com/rwjblue/ember-cli-ic-ajax/issues/6

**Comment by erichonkanen** [comment]
+1 @jme783 thank you! phew

**Comment by ronaldho** [comment]
+1 thank you @jme783 
spent several hours trying to figure out why a push to heroku was failing and this did it :D

**Comment by jme783** [comment]
Nice! Glad you guys were able to fix it

**Comment by kriskhaira** [comment]
@jme783 Any idea how to get your fix to work with Yarn?
